apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-sa
  annotations:
    eks.amazonaws.com/role-arn: YOUR_ROLE_ARN # replace with your IAM role ARN
    # serving.kserve.io/s3-endpoint: s3.us-west-2.amazonaws.com # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    # serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "us-west-2"
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials