apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: gpu
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
  template:
    spec:
      nodeClassRef: 
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: gpu
      requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["g"]
      - key: "karpenter.k8s.aws/instance-gpu-name"
        operator: In
        values: ["a10g"]
      - key: "karpenter.k8s.aws/instance-gpu-count"
        operator: Gt
        values: ["0"]
      - key: "karpenter.k8s.aws/instance-gpu-count"
        operator: Lt
        values: ["10"]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot", "on-demand"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: "kubernetes.io/os"
        operator: In
        values: ["linux"]
      - key: karpenter.k8s.aws/instance-local-nvme
        operator: Gt
        values: ["100"]
  limits:
    nvidia.com/gpu: "10"
  weight: 1
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  # Required, resolves a default ami and userdata
  amiFamily: Ubuntu
  role: KarpenterNodeRole-shijunx-karpenter-demo
  instanceStorePolicy: RAID0
  # Required, discovers subnets to attach to instances
  # Each term in the array of subnetSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  subnetSelectorTerms:
    # Select on any subnet that has the "karpenter.sh/discovery: ${CLUSTER_NAME}"
    # AND the "environment: test" tag OR any subnet with ID "subnet-09fa4a0a8f233a921"
    - tags:
        karpenter.sh/discovery: shijunx-karpenter-demo

  # Required, discovers security groups to attach to instances
  # Each term in the array of securityGroupSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  securityGroupSelectorTerms:
    # Select on any security group that has both the "karpenter.sh/discovery: ${CLUSTER_NAME}" tag
    # AND the "environment: test" tag OR any security group with the "my-security-group" name
    # OR any security group with ID "sg-063d7acfb4b06c82c"
    - tags:
        karpenter.sh/discovery: shijunx-karpenter-demo

  amiSelectorTerms:
  - name: amazon-eks-gpu-node-1.29-v20240531

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3


