apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kserver-cluster
  region: us-west-2
  version: '1.29'
  tags:
    karpenter.sh/discovery: kserver-cluster

iam:
  withOIDC: true

karpenter:
  version: 'v0.36.2' # Exact version must be provided
  createServiceAccount: true # default is false
  withSpotInterruptionQueue: true # adds all required policies and rules for supporting Spot Interruption Queue, default is false

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
