apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mnist-s3"
spec:
  predictor:
    serviceAccountName: s3-sa
    model:
      modelFormat:
        name: tensorflow
      storageUri: "YOUR_S3_URL"
